# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.TextField()),
                ('status', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('check_sql', models.TextField()),
                ('expected_status', models.IntegerField()),
                ('expected', models.TextField()),
                ('status', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Api')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DbConfigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dbname', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('sql', models.FileField(upload_to='./upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('detail', models.TextField()),
                ('error', models.TextField()),
                ('dbresult', models.TextField()),
                ('status', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Case')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Project'),
        ),
        migrations.AddField(
            model_name='dbconfigure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Project'),
        ),
        migrations.AddField(
            model_name='api',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Module'),
        ),
    ]
